import type { Metadata } from 'next';
import localFont from 'next/font/local';

import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'bootstrap/dist/css/bootstrap-grid.min.css';
import './globals.scss';

// import Preloader from '@/components/utilities/Preloader/Preloader';
// import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import BtnTop from '@/components/utilities/BtnTop/BtnTop';
import ScrollToHash from '@/components/utilities/ScrollToHash/ScrollToHash';

const perfograma = localFont({
  src: [
    {
      path: '../public/fonts/perfograma/Perfograma.woff2',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-perfograma',
});

const onest = localFont({
  src: [
    {
      path: '../public/fonts/onset/Onest-Thin.woff2',
      weight: '100',
      style: 'normal',
    },
    {
      path: '../public/fonts/onset/Onest-ExtraLight.woff2',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../public/fonts/onset/Onest-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/onset/Onest-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/onset/Onest-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/onset/Onest-SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/onset/Onest-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/onset/Onest-ExtraBold.woff2',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../public/fonts/onset/Onest-Black.woff2',
      weight: '900',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-onest',
});

const ibm = localFont({
  src: [
    {
      path: '../public/fonts/ibm/IBMPlexMono-Thin.woff2',
      weight: '100',
      style: 'normal',
    },
    {
      path: '../public/fonts/ibm/IBMPlexMono-ThinItalic.woff2',
      weight: '100',
      style: 'italic',
    },
    {
      path: '../public/fonts/ibm/IBMPlexMono-ExtraLight.woff2',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../public/fonts/ibm/IBMPlexMono-Italic.woff2',
      weight: '200',
      style: 'italic',
    },
    {
      path: '../public/fonts/ibm/IBMPlexMono-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/ibm/IBMPlexMono-LightItalic.woff2',
      weight: '300',
      style: 'italic',
    },
    {
      path: '../public/fonts/ibm/IBMPlexMono-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/ibm/IBMPlexMono-Italic.woff2',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../public/fonts/ibm/IBMPlexMono-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/ibm/IBMPlexMono-MediumItalic.woff2',
      weight: '500',
      style: 'italic',
    },
    {
      path: '../public/fonts/ibm/IBMPlexMono-SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/ibm/IBMPlexMono-SemiBoldItalic.woff2',
      weight: '600',
      style: 'italic',
    },
    {
      path: '../public/fonts/ibm/IBMPlexMono-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/ibm/IBMPlexMono-BoldItalic.woff2',
      weight: '700',
      style: 'italic',
    },
  ],
  display: 'swap',
  variable: '--font-ibm',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${perfograma.variable} ${onest.variable} ${ibm.variable}`}>
        {/* <Header /> */}
        <main>{children}</main>
        <Footer />
        <BtnTop />
        <ScrollToHash />
      </body>
    </html>
  );
}
